import type { CampaignAggregate, MetricRow } from './types';
import { fmtCurrency, fmtPercent, groupCampaigns } from './metrics';
import { resultLabel } from './resultTypes';

const UNITS=['Sobral','Fortaleza','Itapipoca','Tianguá','Umirim'] as const;
const strip=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function inferUnit(name:string){const n=strip(name);return UNITS.find(u=>n.includes(strip(u)));}
export function inferCategory(name:string){const n=strip(name); if(/pos med|pos-med|ultra|nutro|med academy/.test(n)) return 'Pós Médica'; if(/medicina|\[med\]/.test(n)) return 'Medicina'; if(/fies/.test(n)) return 'FIES'; if(/vest|ps 26|ps 27|processo seletivo/.test(n)) return 'Vestibular'; if(/institucional|alcance|engaj/.test(n)) return 'Institucional'; if(/evento/.test(n)) return 'Evento'; return 'Outras';}
export function median(values:(number|undefined)[]){const a=values.filter((v):v is number=>v!==undefined&&Number.isFinite(v)).sort((a,b)=>a-b);if(!a.length)return undefined;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
export function resultContext(c:CampaignAggregate){return c.result_indicator?resultLabel(c.result_indicator):'Resultado não informado';}
export function comparable(c:CampaignAggregate, all:CampaignAggregate[]){
  const cat=inferCategory(c.campaign_name), unit=c.unit??inferUnit(c.campaign_name), result=c.result_indicator;
  const others=all.filter(o=>o.campaign_key!==c.campaign_key);
  const sameCategory=others.filter(o=>inferCategory(o.campaign_name)===cat);
  const sameResult=result?sameCategory.filter(o=>o.result_indicator===result):sameCategory;
  const sameUnit=unit?sameResult.filter(o=>(o.unit??inferUnit(o.campaign_name))===unit):sameResult;
  if(sameUnit.length>=3)return {peers:sameUnit,scope:`${cat} • ${unit} • ${resultContext(c)}`};
  if(sameResult.length>=3)return {peers:sameResult,scope:`${cat} • ${resultContext(c)}`};
  if(sameCategory.length>=3)return {peers:sameCategory,scope:`${cat} • resultado misto (fallback)`};
  return {peers:[],scope:`${cat} • amostra insuficiente`};
}
export type Insight={tone:'positive'|'warning'|'info',title:string,evidence:string,confidence:'Alta'|'Média',scope:string,sample:number,source:string,hypothesis:string};
export function campaignInsights(c:CampaignAggregate, all:CampaignAggregate[]){const cmp=comparable(c,all),peers=cmp.peers; const out:Insight[]=[]; const medCpl=median(peers.map(x=>x.cpl)); const medCtr=median(peers.map(x=>x.ctr)); const medCpc=median(peers.map(x=>x.cpc)); const confidence:Insight['confidence']=peers.length>=5?'Alta':'Média'; if(c.cpl!==undefined&&medCpl!==undefined){const d=(c.cpl/medCpl-1)*100;out.push({tone:d<=-15?'positive':d>=25?'warning':'info',title:d<=-15?'CPL abaixo do benchmark contextual':d>=25?'CPL acima do benchmark contextual':'CPL próximo do benchmark contextual',evidence:`${fmtCurrency(c.cpl)} nesta campanha vs ${fmtCurrency(medCpl)} de mediana em ${peers.length} comparáveis (${Math.abs(d).toFixed(0)}% ${d<0?'abaixo':'acima'}).`,confidence,scope:cmp.scope,sample:peers.length,source:'Meta Ads — arquivo importado',hypothesis:d>=25?'Testar uma variável por vez (público, criativo ou oferta) mantendo período e mensuração comparáveis.':'Preservar a configuração como referência de mídia e validar qualidade comercial antes de escalar.'});} if(c.ctr!==undefined&&medCtr!==undefined){const d=(c.ctr/medCtr-1)*100;out.push({tone:d>=15?'positive':d<=-20?'warning':'info',title:d>=15?'CTR acima do histórico comparável':d<=-20?'CTR abaixo do histórico comparável':'CTR dentro da faixa histórica',evidence:`${fmtPercent(c.ctr)} vs mediana ${fmtPercent(medCtr)} (${Math.abs(d).toFixed(0)}% ${d<0?'abaixo':'acima'}).`,confidence,scope:cmp.scope,sample:peers.length,source:'Meta Ads — arquivo importado',hypothesis:d<=-20?'Investigar aderência entre promessa, criativo e público antes de alterar orçamento.':'Usar CTR como sinal de atenção; confirmar conversão e qualidade antes de concluir desempenho.'});} if(c.cpc!==undefined&&medCpc!==undefined&&out.length<3){const d=(c.cpc/medCpc-1)*100;out.push({tone:d<=-15?'positive':d>=25?'warning':'info',title:'Eficiência de clique',evidence:`CPC ${fmtCurrency(c.cpc)} vs mediana ${fmtCurrency(medCpc)} das campanhas comparáveis.`,confidence,scope:cmp.scope,sample:peers.length,source:'Meta Ads — arquivo importado',hypothesis:'Cruzar CPC com CTR e conversão; clique barato isoladamente não prova eficiência de negócio.'});} if((c.spend??0)>0&&c.leads===undefined)out.push({tone:'warning',title:'Qualidade comercial não mensurável',evidence:'Há investimento, mas o indicador de resultado não foi classificado como lead. Não é seguro calcular CPL.',confidence:'Alta',scope:cmp.scope,sample:peers.length,source:'Meta Ads — arquivo importado',hypothesis:'Conectar/importar uma fonte de conversão adequada antes de otimizar por lead.'}); return out.slice(0,3);}
export function dataCoverage(rows:MetricRow[]){const fields=['spend','impressions','reach','link_clicks','results'] as const; const available=fields.filter(f=>rows.some(r=>r[f]!==undefined)); return {available,total:fields.length,pct:Math.round(available.length/fields.length*100)};}
export function portfolioDiscoveries(rows:MetricRow[]){const all=groupCampaigns(rows);const measurable=all.filter(x=>x.cpl!==undefined);const med=median(measurable.map(x=>x.cpl));const contextual=all.flatMap(c=>campaignInsights(c,all).map(i=>({c,i})));const warnings=contextual.filter(x=>x.i.tone==='warning').sort((a,b)=>(b.c.spend??0)-(a.c.spend??0)).slice(0,3);const efficient=contextual.filter(x=>x.i.tone==='positive').sort((a,b)=>(b.c.spend??0)-(a.c.spend??0)).slice(0,3);return {medianCpl:med,warnings,efficient,measurable:measurable.length};}
