import { createFileRoute, Link } from "@tanstack/react-router";
import { z } from "zod";
import { ArrowDownUp, Check, CircleDashed, Megaphone, Search, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { EmptyState, PageHeader, StatusBadge } from "@/components/common/ui-kit";
import { fmtCurrency, fmtNumber, fmtPercent, groupCampaigns } from "@/lib/metrics";
import { inferCategory, inferUnit } from "@/lib/intelligence";
import { campaignCoverage, portfolioRows, useDataset, type CampaignCoverage } from "@/lib/store";

export const Route=createFileRoute("/campanhas/")({validateSearch:z.object({q:z.string().optional(),unit:z.string().optional()}),component:Campaigns});
type Sort='spend'|'leads'|'cpl'|'ctr'|'name';
type CoverageFilter='Todas'|'complete'|'partial'|'campaign_only';

function CoverageBadge({coverage}:{coverage:CampaignCoverage}){
  const complete=coverage.status==='complete';
  const partial=coverage.status==='partial';
  return <div className="group/cov relative inline-flex">
    <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-semibold ${complete?'border-success/35 bg-success/10 text-success':partial?'border-warning/35 bg-warning/10 text-warning':'border-border bg-surface-2 text-muted-foreground'}`}>
      {complete?<ShieldCheck className="size-3.5"/>:<CircleDashed className="size-3.5"/>}{complete?'360° Completa':partial?'Parcial':'Somente campanha'} <b>{coverage.count}/3</b>
    </span>
    <div className="pointer-events-none absolute left-0 top-full z-30 mt-2 hidden w-64 rounded-xl border border-border bg-[#111318] p-3 shadow-2xl group-hover/cov:block">
      <p className="mb-2 text-xs font-semibold text-foreground">Cobertura de dados {coverage.count}/3</p>
      {[['Campanha',coverage.campaign,'Consolidado'],['Conjuntos',coverage.adset,'Públicos / segmentações'],['Anúncios',coverage.ad,'Criativos']].map(([label,ok,desc])=><div key={String(label)} className="flex items-center gap-2 py-1 text-[11px]"><span className={`grid size-4 place-items-center rounded-full ${ok?'bg-success/15 text-success':'bg-surface-2 text-muted-foreground'}`}>{ok?<Check className="size-3"/>:'—'}</span><b>{label}</b><span className="text-muted-foreground">{desc}</span></div>)}
      <p className="mt-2 border-t border-border pt-2 text-[10px] text-muted-foreground">{complete?'Análise 360° disponível com hierarquia completa.':'Importe os níveis ausentes para ampliar a análise.'}</p>
    </div>
  </div>
}

function Campaigns(){
  const ds=useDataset(); const rows=portfolioRows(ds.rows,ds.imports); const search=Route.useSearch();
  const [q,setQ]=useState(search.q??""); const [category,setCategory]=useState('Todas'); const [coverageFilter,setCoverageFilter]=useState<CoverageFilter>('Todas'); const [sort,setSort]=useState<Sort>('spend'); const [page,setPage]=useState(1); const per=25;
  const base=useMemo(()=>groupCampaigns(rows).map(c=>({c,baseRow:rows.find(r=>(r.campaign_id&&c.campaign_id?r.campaign_id===c.campaign_id:r.campaign_name===c.campaign_name))!})).map(x=>({...x,coverage:campaignCoverage(x.baseRow,ds.rows,ds.imports)})),[rows,ds.rows,ds.imports]);
  const data=base.filter(({c})=>c.campaign_name.toLowerCase().includes(q.toLowerCase())).filter(({c})=>!search.unit||search.unit==="Todas as unidades"||(c.unit??inferUnit(c.campaign_name))===search.unit).filter(({c})=>category==='Todas'||inferCategory(c.campaign_name)===category).filter(({coverage})=>coverageFilter==='Todas'||coverage.status===coverageFilter).sort((a,b)=>sort==='name'?a.c.campaign_name.localeCompare(b.c.campaign_name):((b.c[sort] as number|undefined)??-1)-((a.c[sort] as number|undefined)??-1));
  const counts={complete:base.filter(x=>x.coverage.status==='complete').length,partial:base.filter(x=>x.coverage.status==='partial').length,campaign_only:base.filter(x=>x.coverage.status==='campaign_only').length};
  const pages=Math.max(1,Math.ceil(data.length/per)); const shown=data.slice((Math.min(page,pages)-1)*per,Math.min(page,pages)*per);
  return <AppShell><PageHeader title="Campanhas" subtitle="Explore, filtre e identifique quais campanhas já possuem cobertura completa para análise 360°."/>{!rows.length?<EmptyState icon={<Megaphone className="size-9"/>} title="Nenhuma campanha disponível" description="As campanhas aparecerão aqui após a primeira importação." action={<Link to="/importacoes" className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">Importar dados</Link>}/>:<>
    <div className="mb-4 grid gap-3 sm:grid-cols-3"><button onClick={()=>{setCoverageFilter('complete');setPage(1)}} className="panel flex items-center justify-between p-4 text-left hover:border-success/40"><span><b className="block text-sm">Completas 360°</b><span className="text-xs text-muted-foreground">Campanha + conjunto + anúncio</span></span><strong className="text-xl text-success">{counts.complete}</strong></button><button onClick={()=>{setCoverageFilter('partial');setPage(1)}} className="panel flex items-center justify-between p-4 text-left hover:border-warning/40"><span><b className="block text-sm">Parciais</b><span className="text-xs text-muted-foreground">2 de 3 níveis relacionados</span></span><strong className="text-xl text-warning">{counts.partial}</strong></button><button onClick={()=>{setCoverageFilter('campaign_only');setPage(1)}} className="panel flex items-center justify-between p-4 text-left hover:border-border"><span><b className="block text-sm">Somente campanha</b><span className="text-xs text-muted-foreground">Sem detalhe complementar</span></span><strong className="text-xl">{counts.campaign_only}</strong></button></div>
    <section className="panel overflow-hidden"><div className="flex flex-wrap items-center gap-3 border-b border-border p-4"><div className="flex min-w-64 flex-1 items-center gap-2 rounded-lg border border-border bg-surface px-3"><Search className="size-4 text-muted-foreground"/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Buscar campanha..." className="h-10 w-full bg-transparent text-sm outline-none"/></div><SlidersHorizontal className="size-4 text-muted-foreground"/><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}} className="rounded-lg border border-border bg-surface px-3 py-2.5 text-sm"><option>Todas</option>{['Vestibular','Medicina','Pós Médica','FIES','Institucional','Evento','Outras'].map(x=><option key={x}>{x}</option>)}</select><select value={coverageFilter} onChange={e=>{setCoverageFilter(e.target.value as CoverageFilter);setPage(1)}} className="rounded-lg border border-border bg-surface px-3 py-2.5 text-sm"><option value="Todas">Cobertura: todas</option><option value="complete">Completas 3/3</option><option value="partial">Parciais 2/3</option><option value="campaign_only">Somente campanha 1/3</option></select><ArrowDownUp className="size-4 text-muted-foreground"/><select value={sort} onChange={e=>setSort(e.target.value as Sort)} className="rounded-lg border border-border bg-surface px-3 py-2.5 text-sm"><option value="spend">Maior investimento</option><option value="leads">Mais leads</option><option value="cpl">Maior CPL</option><option value="ctr">Maior CTR</option><option value="name">Nome A–Z</option></select><span className="text-xs text-muted-foreground">{data.length} campanhas</span></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-sm"><thead className="text-left text-xs text-muted-foreground"><tr><th className="p-4">Campanha</th><th>Cobertura</th><th>Categoria</th><th>Unidade</th><th>Investimento</th><th>Impressões</th><th>Cliques</th><th>Leads</th><th>CTR</th><th>CPC</th><th>CPL</th><th>Status</th></tr></thead><tbody>{shown.map(({c,coverage})=><tr key={c.campaign_key} className="group border-t border-border hover:bg-surface/70"><td className="p-4"><div className="flex items-center gap-2"><Link to="/campanhas/$campaignKey" params={{campaignKey:c.campaign_key}} className="block max-w-80 font-semibold group-hover:text-primary">{c.campaign_name}</Link>{coverage.status==='complete'?<span title="Análise 360° completa" className="rounded bg-primary/10 px-1.5 py-0.5 text-[9px] font-bold text-primary">360°</span>:null}</div><span className="text-[11px] text-muted-foreground">{c.result_indicator??'Indicador Meta não informado'}</span></td><td><CoverageBadge coverage={coverage}/></td><td><span className="rounded-md bg-surface-2 px-2 py-1 text-xs">{inferCategory(c.campaign_name)}</span></td><td>{c.unit??inferUnit(c.campaign_name)??'—'}</td><td>{fmtCurrency(c.spend)}</td><td>{fmtNumber(c.impressions)}</td><td>{fmtNumber(c.clicks)}</td><td>{fmtNumber(c.leads)}</td><td>{fmtPercent(c.ctr)}</td><td>{fmtCurrency(c.cpc)}</td><td>{fmtCurrency(c.cpl)}</td><td><StatusBadge status={c.status}/></td></tr>)}</tbody></table></div>
    <div className="flex items-center justify-between border-t border-border p-4 text-sm"><span className="text-muted-foreground">Página {Math.min(page,pages)} de {pages} • até {per} por página</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="rounded-lg border border-border px-3 py-1.5 disabled:opacity-30">Anterior</button><button disabled={page>=pages} onClick={()=>setPage(p=>Math.min(pages,p+1))} className="rounded-lg border border-border px-3 py-1.5 disabled:opacity-30">Próxima</button></div></div></section></>}</AppShell>
}
