/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CriativosRouteImport } from './routes/criativos'
import { Route as DiagnosticosRouteImport } from './routes/diagnosticos'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as ImportacoesRouteImport } from './routes/importacoes'
import { Route as OrigemQualidadeRouteImport } from './routes/origem-qualidade'
import { Route as PublicosRouteImport } from './routes/publicos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as VisaoGeralRouteImport } from './routes/visao-geral'
import { Route as CampanhasIndexRouteImport } from './routes/campanhas.index'
import { Route as CampanhasCampaignKeyRouteImport } from './routes/campanhas.$campaignKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CriativosRoute = CriativosRouteImport.update({
  id: '/criativos',
  path: '/criativos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticosRoute = DiagnosticosRouteImport.update({
  id: '/diagnosticos',
  path: '/diagnosticos',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacoesRoute = ImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrigemQualidadeRoute = OrigemQualidadeRouteImport.update({
  id: '/origem-qualidade',
  path: '/origem-qualidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicosRoute = PublicosRouteImport.update({
  id: '/publicos',
  path: '/publicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaoGeralRoute = VisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasIndexRoute = CampanhasIndexRouteImport.update({
  id: '/campanhas/',
  path: '/campanhas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasCampaignKeyRoute = CampanhasCampaignKeyRouteImport.update({
  id: '/campanhas/$campaignKey',
  path: '/campanhas/$campaignKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criativos': typeof CriativosRoute
  '/diagnosticos': typeof DiagnosticosRoute
  '/funil': typeof FunilRoute
  '/importacoes': typeof ImportacoesRoute
  '/origem-qualidade': typeof OrigemQualidadeRoute
  '/publicos': typeof PublicosRoute
  '/relatorios': typeof RelatoriosRoute
  '/visao-geral': typeof VisaoGeralRoute
  '/campanhas/$campaignKey': typeof CampanhasCampaignKeyRoute
  '/campanhas/': typeof CampanhasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criativos': typeof CriativosRoute
  '/diagnosticos': typeof DiagnosticosRoute
  '/funil': typeof FunilRoute
  '/importacoes': typeof ImportacoesRoute
  '/origem-qualidade': typeof OrigemQualidadeRoute
  '/publicos': typeof PublicosRoute
  '/relatorios': typeof RelatoriosRoute
  '/visao-geral': typeof VisaoGeralRoute
  '/campanhas/$campaignKey': typeof CampanhasCampaignKeyRoute
  '/campanhas': typeof CampanhasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criativos': typeof CriativosRoute
  '/diagnosticos': typeof DiagnosticosRoute
  '/funil': typeof FunilRoute
  '/importacoes': typeof ImportacoesRoute
  '/origem-qualidade': typeof OrigemQualidadeRoute
  '/publicos': typeof PublicosRoute
  '/relatorios': typeof RelatoriosRoute
  '/visao-geral': typeof VisaoGeralRoute
  '/campanhas/$campaignKey': typeof CampanhasCampaignKeyRoute
  '/campanhas/': typeof CampanhasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparar'
    | '/configuracoes'
    | '/criativos'
    | '/diagnosticos'
    | '/funil'
    | '/importacoes'
    | '/origem-qualidade'
    | '/publicos'
    | '/relatorios'
    | '/visao-geral'
    | '/campanhas/$campaignKey'
    | '/campanhas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comparar'
    | '/configuracoes'
    | '/criativos'
    | '/diagnosticos'
    | '/funil'
    | '/importacoes'
    | '/origem-qualidade'
    | '/publicos'
    | '/relatorios'
    | '/visao-geral'
    | '/campanhas/$campaignKey'
    | '/campanhas'
  id:
    | '__root__'
    | '/'
    | '/comparar'
    | '/configuracoes'
    | '/criativos'
    | '/diagnosticos'
    | '/funil'
    | '/importacoes'
    | '/origem-qualidade'
    | '/publicos'
    | '/relatorios'
    | '/visao-geral'
    | '/campanhas/$campaignKey'
    | '/campanhas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompararRoute: typeof CompararRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CriativosRoute: typeof CriativosRoute
  DiagnosticosRoute: typeof DiagnosticosRoute
  FunilRoute: typeof FunilRoute
  ImportacoesRoute: typeof ImportacoesRoute
  OrigemQualidadeRoute: typeof OrigemQualidadeRoute
  PublicosRoute: typeof PublicosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  VisaoGeralRoute: typeof VisaoGeralRoute
  CampanhasCampaignKeyRoute: typeof CampanhasCampaignKeyRoute
  CampanhasIndexRoute: typeof CampanhasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criativos': {
      id: '/criativos'
      path: '/criativos'
      fullPath: '/criativos'
      preLoaderRoute: typeof CriativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosticos': {
      id: '/diagnosticos'
      path: '/diagnosticos'
      fullPath: '/diagnosticos'
      preLoaderRoute: typeof DiagnosticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacoes': {
      id: '/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof ImportacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origem-qualidade': {
      id: '/origem-qualidade'
      path: '/origem-qualidade'
      fullPath: '/origem-qualidade'
      preLoaderRoute: typeof OrigemQualidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicos': {
      id: '/publicos'
      path: '/publicos'
      fullPath: '/publicos'
      preLoaderRoute: typeof PublicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visao-geral': {
      id: '/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof VisaoGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas/': {
      id: '/campanhas/'
      path: '/campanhas'
      fullPath: '/campanhas/'
      preLoaderRoute: typeof CampanhasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas/$campaignKey': {
      id: '/campanhas/$campaignKey'
      path: '/campanhas/$campaignKey'
      fullPath: '/campanhas/$campaignKey'
      preLoaderRoute: typeof CampanhasCampaignKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompararRoute: CompararRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CriativosRoute: CriativosRoute,
  DiagnosticosRoute: DiagnosticosRoute,
  FunilRoute: FunilRoute,
  ImportacoesRoute: ImportacoesRoute,
  OrigemQualidadeRoute: OrigemQualidadeRoute,
  PublicosRoute: PublicosRoute,
  RelatoriosRoute: RelatoriosRoute,
  VisaoGeralRoute: VisaoGeralRoute,
  CampanhasCampaignKeyRoute: CampanhasCampaignKeyRoute,
  CampanhasIndexRoute: CampanhasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
